# Generated by Django 2.1 on 2018-09-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=256, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Second name'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='size',
            field=models.IntegerField(null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Username'),
        ),
    ]
