# Generated by Django 2.1 on 2018-09-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20180912_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='last_setup_spam_message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
