# Generated by Django 2.1 on 2018-09-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botuser_last_setup_spam_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Is premium'),
        ),
    ]
