# Generated by Django 2.1 on 2018-09-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_auto_20180912_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size'),
        ),
    ]
