# Generated by Django 2.1 on 2018-09-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_botuser_last_referral_program_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='setup_spam_checked_sizes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
