# Generated by Django 2.1 on 2018-09-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_botuser_last_premium_discounts_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='last_premium_discounts_invoice_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
