# Generated by Django 2.1 on 2018-09-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_botuser_last_premium_discounts_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='inviter_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Inviter id'),
        ),
    ]
