# Generated by Django 2.1 on 2018-09-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_botuser_inviter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='amount_of_referrals',
            field=models.IntegerField(default=0, verbose_name='Amount of referrals'),
        ),
    ]
