# Generated by Django 2.1 on 2018-09-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_statistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
