# Generated by Django 2.1 on 2018-09-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_botuser_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'Просмотр', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AddField(
            model_name='botuser',
            name='sizes',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Размеры'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='amount_of_referrals',
            field=models.IntegerField(default=0, verbose_name='Количество приглашенных'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='configured',
            field=models.BooleanField(default=False, verbose_name='Рассылка настроена'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Пользователь отписался от бота'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=256, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='inviter_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID пригласителя'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='is_paid_premium',
            field=models.BooleanField(default=False, verbose_name='Платный премиум аккаунт'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.BigIntegerField(unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='botuser',
            name='username',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Логин'),
        ),
    ]
