# Generated by Django 2.1 on 2018-09-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_botuser_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('button', models.CharField(choices=[('referral_program', 'referral_program'), ('rating', 'rating'), ('invite', 'invite'), ('premium', 'premium'), ('setup_spam', 'setup_spam'), ('callback', 'callback')], max_length=16)),
            ],
        ),
    ]
