# Generated by Django 2.1 on 2018-09-17 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='last_flood_message_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 15, 34, 16, 766913)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botuser',
            name='last_messages_time',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
