# Generated by Django 2.1 on 2018-09-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_auto_20180917_1534'),
    ]

    operations = [
        migrations.RemoveField(model_name='botuser', name='last_flood_message_time'),
        migrations.AddField(model_name='botuser', name='last_flood_message_time', field=models.FloatField(default=0))
#        migrations.AlterField(
#            model_name='botuser',
#            name='last_flood_message_time',
#            field=models.FloatField(default=0),
#        ),
    ]
