# Generated by Django 2.1 on 2018-09-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_auto_20180917_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='last_flood_message_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
