# Generated by Django 2.1 on 2018-09-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0021_auto_20180917_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=256, verbose_name='Логин')),
                ('password', models.CharField(max_length=256, verbose_name='Пароль')),
                ('content_management_rights', models.BooleanField(verbose_name='Менеджмент контента')),
                ('support_rights', models.BooleanField(verbose_name='Поддержка')),
            ],
        ),
    ]
