# Generated by Django 2.1 on 2018-09-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
