# Generated by Django 2.1 on 2018-09-20 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0023_auto_20180919_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='login',
            field=models.CharField(max_length=256, unique=True, verbose_name='Логин'),
        ),
    ]
