# Generated by Django 2.1 on 2018-09-20 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_auto_20180920_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='base',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
