# Generated by Django 2.1 on 2018-09-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_auto_20180920_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostponedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('post', 'Пост'), ('offer', 'Оффер')], max_length=5, verbose_name='Тип публикации')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('text', models.TextField(max_length=200, verbose_name='Текст (форматированный)')),
            ],
            options={
                'verbose_name': 'Отложенный пост',
                'verbose_name_plural': 'Отложенные посты',
            },
        ),
    ]
