# Generated by Django 2.1 on 2018-09-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_postponedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postponedpost',
            name='type',
            field=models.CharField(choices=[('post', 'Пост'), ('offer', 'Оффер')], default='post', max_length=5, verbose_name='Тип публикации'),
        ),
    ]
