# Generated by Django 2.1 on 2018-09-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0032_auto_20180926_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='Текст (форматированный)')),
            ],
            options={
                'verbose_name': 'Черновик',
                'verbose_name_plural': 'Черновики',
            },
        ),
        migrations.AlterField(
            model_name='postponedpost',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Текст (форматированный)'),
        ),
    ]
