# Generated by Django 2.1 on 2018-09-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0033_auto_20180926_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='title',
            field=models.CharField(default='title', max_length=100, verbose_name='Название черновика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draft',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Текст (форматированный, 200 символов)'),
        ),
        migrations.AlterField(
            model_name='postponedpost',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Текст (форматированный, 200 символов)'),
        ),
    ]
