# Generated by Django 2.1 on 2018-09-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0035_auto_20180926_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
