# Generated by Django 2.1 on 2018-09-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0037_auto_20180927_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponedpost',
            name='offer_gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('all', 'Все')], default='male', max_length=6, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_new_users',
            field=models.BooleanField(default=False, verbose_name='Новые пользователи'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_premium',
            field=models.BooleanField(default=False, verbose_name='Премиум'),
        ),
    ]
