# Generated by Django 2.1 on 2018-09-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0039_auto_20180927_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponedpost',
            name='buttons',
            field=models.TextField(blank=True, null=True, verbose_name='Кнопки (формат описания кнопок - вверху страницы)'),
        ),
    ]
