# Generated by Django 2.1 on 2018-09-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0041_auto_20180927_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='text',
            field=models.TextField(max_length=200, verbose_name='Текст (форматированный, 200 символов с учетом размеров обуви)'),
        ),
    ]
