# Generated by Django 2.1 on 2018-09-27 10:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0042_auto_20180927_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponedpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
