# Generated by Django 2.1 on 2018-09-27 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0043_postponedpost_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponedpost',
            name='postpone',
            field=models.BooleanField(default=False, verbose_name='Отложить'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='postpone_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0), verbose_name='Время публикации'),
        ),
    ]
