# Generated by Django 2.1 on 2018-09-27 12:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0044_auto_20180927_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponedpost',
            name='draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Draft', verbose_name='Черновик'),
        ),
        migrations.AlterField(
            model_name='postponedpost',
            name='postpone_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 1, 0, 0), verbose_name='Время публикации (часовой пояс UTC)'),
        ),
    ]
