# Generated by Django 2.1 on 2018-09-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0045_auto_20180927_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postponedpost',
            name='buttons',
            field=models.TextField(blank=True, null=True, verbose_name='Кнопки-ссылки (формат описания - вверху страницы)'),
        ),
    ]
