# Generated by Django 2.1 on 2018-09-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0047_auto_20180927_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponedpost',
            name='post_0_referrals',
            field=models.BooleanField(default=False, verbose_name='У кого 0 рефералов'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='post_1_referrals',
            field=models.BooleanField(default=False, verbose_name='У кого 1 рефералов'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='post_2_referrals',
            field=models.BooleanField(default=False, verbose_name='У кого 2 рефералов'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='post_3_and_more_referrals',
            field=models.BooleanField(default=False, verbose_name='У кого 3 и более рефералов'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='post_all',
            field=models.BooleanField(default=True, verbose_name='Все пользователи'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='post_need_spam_setup',
            field=models.BooleanField(default=False, verbose_name='Кто не настроил рассылку'),
        ),
    ]
