# Generated by Django 2.1 on 2018-09-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0048_auto_20180927_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponedpost',
            name='offer_sizes',
            field=models.CharField(default='40 40.5', max_length=1024, verbose_name='Размеры (через пробел, с шагом 0.5)'),
            preserve_default=False,
        ),
    ]
