# Generated by Django 2.1 on 2018-09-27 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0049_postponedpost_offer_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponedpost',
            name='sent',
            field=models.DateField(default=datetime.date(2040, 1, 1)),
        ),
        migrations.AlterField(
            model_name='postponedpost',
            name='offer_sizes',
            field=models.CharField(max_length=1024, verbose_name='Размеры EU (через пробел, с шагом 0.5)'),
        ),
        migrations.AlterField(
            model_name='postponedpost',
            name='offer_sizes_type',
            field=models.CharField(choices=[('EU', 'EU'), ('US', 'US'), ('UK', 'UK')], default='EU', max_length=2, verbose_name='Размерность (которая отображается пользователям)'),
        ),
    ]
