# Generated by Django 2.1 on 2018-09-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0052_auto_20180927_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponedpost',
            name='button_1_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка 1-й кнопки'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='button_1_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст 1-й кнопки'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='button_2_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка 2-й кнопки'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='button_2_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст 2-й кнопки'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='button_3_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка 3-й кнопки'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='button_3_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст 3-й кнопки'),
        ),
    ]
