# Generated by Django 2.1 on 2018-09-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0053_auto_20180927_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postponedpost',
            name='buttons',
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='amount_of_buttons',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0, verbose_name='Количество кнопок'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='button_4_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка 4-й кнопки'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='button_4_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст 4-й кнопки'),
        ),
    ]
