# Generated by Django 2.1 on 2018-09-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0054_auto_20180928_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postponedpost',
            name='amount_of_buttons',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=0, verbose_name='Количество кнопок-ссылок'),
        ),
    ]
