# Generated by Django 2.1 on 2018-09-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0056_auto_20180928_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postponedpost',
            name='offer_sizes',
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_36',
            field=models.BooleanField(default=False, verbose_name='36 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_36_5',
            field=models.BooleanField(default=False, verbose_name='36.5 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_37',
            field=models.BooleanField(default=False, verbose_name='37 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_37_5',
            field=models.BooleanField(default=False, verbose_name='37.5 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_38',
            field=models.BooleanField(default=False, verbose_name='38 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_38_5',
            field=models.BooleanField(default=False, verbose_name='38.5 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_39',
            field=models.BooleanField(default=False, verbose_name='39 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_39_5',
            field=models.BooleanField(default=False, verbose_name='39.5 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_40',
            field=models.BooleanField(default=False, verbose_name='40 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_40_5',
            field=models.BooleanField(default=False, verbose_name='40.5 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_41',
            field=models.BooleanField(default=False, verbose_name='41 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_41_5',
            field=models.BooleanField(default=False, verbose_name='41.5 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_42',
            field=models.BooleanField(default=False, verbose_name='42 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_42_5',
            field=models.BooleanField(default=False, verbose_name='42.5 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_43',
            field=models.BooleanField(default=False, verbose_name='43 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_43_5',
            field=models.BooleanField(default=False, verbose_name='43.5 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_44',
            field=models.BooleanField(default=False, verbose_name='44 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_44_5',
            field=models.BooleanField(default=False, verbose_name='44.5 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_45',
            field=models.BooleanField(default=False, verbose_name='45 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_45_5',
            field=models.BooleanField(default=False, verbose_name='45.5 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_46',
            field=models.BooleanField(default=False, verbose_name='46 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_46_5',
            field=models.BooleanField(default=False, verbose_name='46.5 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_47',
            field=models.BooleanField(default=False, verbose_name='47 EU'),
        ),
        migrations.AddField(
            model_name='postponedpost',
            name='offer_size_47_5',
            field=models.BooleanField(default=False, verbose_name='47.5 EU'),
        ),
    ]
