# Generated by Django 2.1 on 2018-09-28 09:48

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0057_auto_20180928_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postponedpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=bot.models.PostponedPost.get_image_path, validators=[bot.models.PostponedPost.validate_image], verbose_name='Изображение (до 1МБ)'),
        ),
    ]
