# Generated by Django 2.1 on 2018-09-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0058_auto_20180928_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Первый запуск бота (часовой пояс UTC)'),
        ),
        migrations.AlterField(
            model_name='postponedpost',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания (часовой пояс UTC)'),
        ),
    ]
