# Generated by Django 2.1 on 2018-10-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0059_auto_20180928_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='postponedpost',
            name='amount_of_receivers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
