# Generated by Django 2.1 on 2018-10-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0063_auto_20181009_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDialogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
            },
        ),
    ]
