# Generated by Django 2.1 on 2018-10-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0067_auto_20181010_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст (форматированный, 200 символов для постов с картинкой сверху)'),
        ),
        migrations.AlterField(
            model_name='postponedpost',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст (форматированный, 200 символов для постов с картинкой сверху)'),
        ),
    ]
