# Generated by Django 2.1 on 2018-10-11 17:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0069_auto_20181011_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdialogue',
            name='last_message',
            field=models.CharField(blank=True, default='', max_length=203, verbose_name='Последнее сообщение'),
        ),
        migrations.AddField(
            model_name='feedbackdialogue',
            name='last_message_sender',
            field=models.CharField(choices=[('user', 'Пользователь'), ('support', 'Поддержка')], default='user', max_length=7, verbose_name='Отправитель последнего сообщения'),
        ),
        migrations.AlterField(
            model_name='feedbackdialogue',
            name='last_message_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 17, 14, 24, 593713, tzinfo=utc), verbose_name='Время последнего сообщения (часовой пояс UTC)'),
        ),
        migrations.AlterField(
            model_name='feedbackdialogue',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт'), ('ignored', 'Игнор')], default='open', max_length=7, verbose_name='Статус'),
        ),
    ]
