# Generated by Django 2.1 on 2018-10-11 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0070_auto_20181011_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackdialogue',
            name='last_message',
        ),
        migrations.AlterField(
            model_name='feedbackdialogue',
            name='last_message_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 17, 28, 31, 485184, tzinfo=utc), verbose_name='Время последнего сообщения (часовой пояс UTC)'),
        ),
    ]
