# Generated by Django 2.1 on 2018-10-15 18:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0072_auto_20181011_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdialogue',
            name='last_message_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 18, 50, 49, 25503, tzinfo=utc), verbose_name='Время последнего сообщения (часовой пояс UTC)'),
        ),
        migrations.AlterField(
            model_name='postponedpost',
            name='image_place',
            field=models.CharField(choices=[('bottom', 'Снизу')], default='bottom', max_length=6, verbose_name='Расположение изображения'),
        ),
    ]
