# Generated by Django 2.1 on 2018-10-15 22:43

import bot.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0073_auto_20181015_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdialogue',
            name='button_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка кнопки'),
        ),
        migrations.AddField(
            model_name='feedbackdialogue',
            name='button_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='feedbackdialogue',
            name='draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.Draft', verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='feedbackdialogue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=bot.models.FeedbackDialogue.get_image_path, validators=[bot.models.FeedbackDialogue.validate_image], verbose_name='Изображение (до 1МБ)'),
        ),
        migrations.AddField(
            model_name='feedbackdialogue',
            name='image_place',
            field=models.CharField(choices=[('bottom', 'Снизу')], default='bottom', max_length=6, verbose_name='Расположение изображения'),
        ),
        migrations.AddField(
            model_name='feedbackdialogue',
            name='message',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Текст (форматированный)'),
        ),
        migrations.AlterField(
            model_name='feedbackdialogue',
            name='last_message_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 15, 22, 43, 53, 236339, tzinfo=utc), verbose_name='Время последнего сообщения (часовой пояс UTC)'),
        ),
    ]
